# Generated by Django 4.2.4 on 2024-04-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_users_created_at_users_updated_at_alter_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='NewUser', max_length=128, unique=True),
        ),
    ]
