# Generated by Django 4.2.4 on 2024-04-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_users_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='NewUser', max_length=128),
        ),
    ]
