# Generated by Django 4.2.4 on 2024-04-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_alter_users_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='user_name',
        ),
    ]
