# Generated by Django 4.2.4 on 2024-04-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_rename_username_users_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_name',
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='NewUser', max_length=128),
        ),
    ]
