# Generated by Django 4.2.4 on 2024-04-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_remove_users_user_name_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
