# Generated by Django 4.2.4 on 2024-04-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_remove_users_email_remove_users_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='user_id',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('Tenant', 'Tenant'), ('Owner', 'Owner')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, default='NewUser', max_length=128, null=True),
        ),
    ]
